# Generated by Django 4.2 on 2023-04-14 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                ("owner", models.CharField(max_length=16)),
                ("organization", models.CharField(max_length=16)),
                ("registered_in", models.DateTimeField(verbose_name="date published")),
                ("last_seen", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                ("password", models.CharField(max_length=16)),
                (
                    "groups",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app00.group"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app00.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrinterOuts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date published")),
                ("state", models.IntegerField(default=0)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app00.file"
                    ),
                ),
                (
                    "send_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app00.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="upload_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app00.user"
            ),
        ),
    ]
