# Generated by Django 4.2 on 2023-04-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app00", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Group",
            new_name="Groupo",
        ),
    ]
