# Generated by Django 4.2 on 2023-04-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app00", "0002_rename_group_groupo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="printerouts",
            old_name="date",
            new_name="registered_in",
        ),
    ]
