# Generated by Django 4.2 on 2023-04-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00", "0003_rename_date_printerouts_registered_in"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="path",
            new_name="document_name",
        ),
        migrations.AddField(
            model_name="file",
            name="job_status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="file",
            name="local_user_name",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="file",
            name="total_pages",
            field=models.IntegerField(default=0),
        ),
    ]
