# Generated by Django 4.2 on 2023-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00", "0004_rename_path_file_document_name_file_job_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="printer_name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
