# Generated by Django 4.2 on 2023-04-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app00", "0006_printer_driver_name_printer_port_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printer",
            name="driver_name",
        ),
    ]
