# Generated by Django 4.2 on 2023-04-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00", "0007_remove_printer_driver_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="port_name",
            field=models.CharField(max_length=32),
        ),
    ]
