# Generated by Django 4.2 on 2023-04-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00", "0009_printer_driver_name_alter_printer_port_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="printerouts",
            old_name="state",
            new_name="job_status",
        ),
        migrations.RenameField(
            model_name="printerouts",
            old_name="send_by",
            new_name="upload_by",
        ),
        migrations.RemoveField(
            model_name="printerouts",
            name="file",
        ),
        migrations.AddField(
            model_name="printerouts",
            name="document_name",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printerouts",
            name="local_user_name",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printerouts",
            name="printer_name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printerouts",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="printerouts",
            name="total_pages",
            field=models.IntegerField(default=0),
        ),
    ]
