# Generated by Django 4.2 on 2023-04-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app00", "0011_delete_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="local_id",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
